# Generated by Django 4.2.6 on 2023-10-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=100)),
                ('Completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Todos',
            },
        ),
    ]
